#!/usr/bin/env python3
"""
fetch_odds.py — Fetches 2026 US Open odds and writes odds.json

Usage:
    python3 fetch_odds.py

Requires: pip install requests beautifulsoup4

Tries these sources in order until one works:
  1. VegasInsider (most reliable)
  2. The Odds API (if you have a key in ODDS_API_KEY env var or odds_api_key.txt)
  3. DraftKings Network article (public, no key needed)
  4. CBS Sports article (public, no key needed)
"""

import json, re, sys, os, datetime, time
from pathlib import Path

try:
    import requests
    from bs4 import BeautifulSoup
except ImportError:
    print("Installing dependencies...")
    os.system(f"{sys.executable} -m pip install requests beautifulsoup4 -q")
    import requests
    from bs4 import BeautifulSoup

OUTPUT_FILE = Path(__file__).parent / "odds.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Cache-Control": "no-cache",
}

# Known player name variations to normalize
NAME_MAP = {
    "Rory Mcilroy": "Rory McIlroy",
    "Rory McIlory": "Rory McIlroy",
    "Xander Schauffele": "Xander Schauffele",
    "Ludvig Aberg": "Ludvig Åberg",
    "Ludvig Åberg": "Ludvig Åberg",
    "Joaquin Niemann": "Joaquín Niemann",
    "Nicolai Hojgaard": "Nicolai Højgaard",
    "Rasmus Hojgaard": "Rasmus Højgaard",
    "Sami Valimaki": "Sami Välimäki",
    "Matt Fitzpatrick": "Matt Fitzpatrick",
    "Matthew Fitzpatrick": "Matt Fitzpatrick",
    "Si Woo Kim": "Si Woo Kim",
    "JT Poston": "J.T. Poston",
    "J.T. Poston": "J.T. Poston",
    "JJ Spaun": "J.J. Spaun",
    "J.J. Spaun": "J.J. Spaun",
    "Hideki Matsuyama": "Hideki Matsuyama",
}

def normalize_name(name):
    name = name.strip()
    return NAME_MAP.get(name, name)

def fmt_odds(price):
    """Convert integer to American odds string."""
    try:
        n = int(price)
        return f"+{n}" if n >= 0 else str(n)
    except:
        return None

def load_existing():
    """Load existing odds.json as a base."""
    try:
        with open(OUTPUT_FILE) as f:
            data = json.load(f)
        return data.get("odds", {})
    except:
        return {}

def save_odds(odds_dict, source):
    data = {
        "odds": odds_dict,
        "exportedAt": datetime.datetime.utcnow().isoformat() + "Z",
        "source": source,
        "note": "Generated by fetch_odds.py — push to GitHub root."
    }
    with open(OUTPUT_FILE, "w") as f:
        json.dump(data, f, indent=2)
    print(f"✓ Saved {len(odds_dict)} players to {OUTPUT_FILE}")
    print(f"  Source: {source}")

# ── Source 1: The Odds API ────────────────────────────────────────────────────
def try_odds_api():
    # Check for API key in env var or file
    api_key = os.environ.get("ODDS_API_KEY", "")
    if not api_key:
        key_file = Path(__file__).parent / "odds_api_key.txt"
        if key_file.exists():
            api_key = key_file.read_text().strip()
    if not api_key:
        print("  Skipping The Odds API — no key found (set ODDS_API_KEY env var or create odds_api_key.txt)")
        return None

    print("  Trying The Odds API...")
    try:
        r = requests.get(
            "https://api.the-odds-api.com/v4/sports/golf_pga_championship_winner/odds",
            params={"regions": "us", "markets": "outrights", "oddsFormat": "american", "apiKey": api_key},
            headers=HEADERS, timeout=15
        )
        remaining = r.headers.get("x-requests-remaining", "?")
        print(f"  Requests remaining: {remaining}")
        if r.status_code == 404:
            print("  Market not active (tournament may be live — futures closed)")
            return None
        r.raise_for_status()
        data = r.json()
        odds = {}
        for book in data:
            for market in book.get("markets", []):
                for outcome in market.get("outcomes", []):
                    name = normalize_name(outcome["name"])
                    price = outcome["price"]
                    formatted = fmt_odds(price)
                    if formatted and (name not in odds or abs(price) < abs(int(odds[name]))):
                        odds[name] = formatted
        if odds:
            print(f"  ✓ Got {len(odds)} players from The Odds API")
            return odds, "The Odds API"
        print("  No odds returned")
        return None
    except Exception as e:
        print(f"  The Odds API failed: {e}")
        return None

# ── Source 2: DraftKings Network article ─────────────────────────────────────
def try_draftkings_network():
    print("  Trying DraftKings Network...")
    urls = [
        "https://dknetwork.draftkings.com/2026/06/2026-us-open-odds/",
        "https://dknetwork.draftkings.com/2026/06/2026-us-open-odds-full-field/",
    ]
    for url in urls:
        try:
            r = requests.get(url, headers=HEADERS, timeout=15)
            if r.status_code != 200:
                continue
            soup = BeautifulSoup(r.text, "html.parser")
            text = soup.get_text(" ", strip=True)
            odds = parse_odds_from_text(text)
            if len(odds) >= 10:
                print(f"  ✓ Got {len(odds)} players from DraftKings Network")
                return odds, "DraftKings Network"
        except Exception as e:
            print(f"  DraftKings Network ({url}): {e}")
    return None

# ── Source 3: CBS Sports ──────────────────────────────────────────────────────
def try_cbssports():
    print("  Trying CBS Sports...")
    urls = [
        "https://www.cbssports.com/golf/news/2026-us-open-odds-picks-scottie-scheffler-rory-mcilroy-predictions/",
        "https://www.cbssports.com/golf/news/2026-us-open-odds-date-field-course-picks-predictions-best-bets/",
    ]
    for url in urls:
        try:
            r = requests.get(url, headers=HEADERS, timeout=15)
            if r.status_code != 200:
                continue
            soup = BeautifulSoup(r.text, "html.parser")
            text = soup.get_text(" ", strip=True)
            odds = parse_odds_from_text(text)
            if len(odds) >= 10:
                print(f"  ✓ Got {len(odds)} players from CBS Sports")
                return odds, "CBS Sports"
        except Exception as e:
            print(f"  CBS Sports ({url}): {e}")
    return None

# ── Source 4: VegasInsider ────────────────────────────────────────────────────
def try_vegasinsider():
    print("  Trying VegasInsider...")
    try:
        r = requests.get(
            "https://www.vegasinsider.com/golf/odds/us-open/",
            headers=HEADERS, timeout=15, verify=False
        )
        if r.status_code != 200:
            return None
        soup = BeautifulSoup(r.text, "html.parser")
        text = soup.get_text(" ", strip=True)
        odds = parse_odds_from_text(text)
        if len(odds) >= 10:
            print(f"  ✓ Got {len(odds)} players from VegasInsider")
            return odds, "VegasInsider"
    except Exception as e:
        print(f"  VegasInsider: {e}")
    return None

# ── Text parser ───────────────────────────────────────────────────────────────
def parse_odds_from_text(text):
    """
    Parse player odds from free-text pages.
    Handles patterns like:
      "Scottie Scheffler +480"
      "Rory McIlroy +850"
      "Scottie Scheffler     +480"
    """
    odds = {}
    # Pattern: First Last +NNNN or First Last -NNN
    pattern = re.compile(
        r'([A-Z][a-záàäâéèëêíìïîóòöôúùüûýñãõæøåčšž\u00C0-\u024F]+'
        r'(?:\s+[A-Z][a-záàäâéèëêíìïîóòöôúùüûýñãõæøåčšž\u00C0-\u024F]+)+)'
        r'\s{0,10}([+-]\d{3,6})\b'
    )
    for match in pattern.finditer(text):
        name = normalize_name(match.group(1).strip())
        price_str = match.group(2)
        # Skip obviously wrong matches (short names, scores, etc.)
        if len(name) < 8:
            continue
        # Skip if it looks like a score (e.g. -8, +3) rather than odds
        try:
            val = int(price_str)
            if abs(val) < 100:
                continue  # odds are always >=100
        except:
            continue
        formatted = fmt_odds(val)
        if formatted:
            # Keep best (lowest) odds if duplicate
            if name not in odds or abs(val) < abs(int(odds[name])):
                odds[name] = formatted
    return odds

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print("=" * 50)
    print("US Open Odds Fetcher")
    print("=" * 50)

    existing = load_existing()
    print(f"Existing odds.json: {len(existing)} players\n")

    result = None
    for source_fn in [try_vegasinsider, try_odds_api, try_draftkings_network, try_cbssports]:
        result = source_fn()
        if result:
            break
        print()

    if result:
        new_odds, source_name = result
        # Merge: new data wins, keep existing for any players not found
        merged = {**existing, **new_odds}
        save_odds(merged, source_name)
        # Print summary
        print(f"\nTop 10 odds:")
        sorted_odds = sorted(merged.items(), key=lambda x: int(x[1].replace("+","")))
        for name, odds in sorted_odds[:10]:
            print(f"  {name:<30} {odds}")
    else:
        print("\n⚠ All sources failed. Keeping existing odds.json unchanged.")
        print("  You can manually update odds.json with the current lines.")
        if not existing:
            print("  No existing odds found — creating with seed data.")
            save_odds(SEED_ODDS, "Manual seed")

if __name__ == "__main__":
    main()