#!/usr/bin/env python3
"""
fetch_odds.py — Fetches 2026 Open Championship (British Open) odds and writes odds.json

Usage:
    python3 fetch_odds.py

Requires: pip install requests beautifulsoup4

Tries these sources in order until one works (all public, no API key needed):
  1. CBS Sports — main odds article (updated daily, static HTML, easiest to scrape)
  2. CBS Sports — secondary odds article (kept as a backup in case the slug above changes)
  3. Bleacher Report — field/odds preview article

Note: VegasInsider and The Odds API were removed. VegasInsider's odds tables are
JS-rendered (a bare requests/BeautifulSoup GET returns mostly boilerplate copy,
not numbers), and The Odds API needs a paid/free-tier key, which this version
intentionally avoids. The old DraftKings Network URLs were also removed since
they were guessed slugs (.../2026/06/2026-us-open-odds/) that 404 as soon as
the real published slug differs — CBS's URLs below were verified live.
"""

import json, re, sys, os, datetime
from pathlib import Path

try:
    import requests
    from bs4 import BeautifulSoup
except ImportError:
    print("Installing dependencies...")
    os.system(f"{sys.executable} -m pip install requests beautifulsoup4 -q")
    import requests
    from bs4 import BeautifulSoup

OUTPUT_FILE = Path(__file__).parent / "odds.json"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Cache-Control": "no-cache",
}

# Known player name variations to normalize
NAME_MAP = {
    "Rory Mcilroy": "Rory McIlroy",
    "Rory McIlory": "Rory McIlroy",
    "Xander Schauffele": "Xander Schauffele",
    "Ludvig Aberg": "Ludvig Åberg",
    "Ludvig Åberg": "Ludvig Åberg",
    "Joaquin Niemann": "Joaquín Niemann",
    "Nicolai Hojgaard": "Nicolai Højgaard",
    "Nicolai Højgaard": "Nicolai Højgaard",
    "Rasmus Hojgaard": "Rasmus Højgaard",
    "Rasmus Højgaard": "Rasmus Højgaard",
    "Sami Valimaki": "Sami Välimäki",
    "Matt Fitzpatrick": "Matt Fitzpatrick",
    "Matthew Fitzpatrick": "Matt Fitzpatrick",
    "Alex Fitzpatrick": "Alex Fitzpatrick",
    "Si Woo Kim": "Si Woo Kim",
    "JT Poston": "J.T. Poston",
    "J.T. Poston": "J.T. Poston",
    "JJ Spaun": "J.J. Spaun",
    "J.J. Spaun": "J.J. Spaun",
    "Hideki Matsuyama": "Hideki Matsuyama",
    "Matt Mccarty": "Matt McCarty",
}

# Fallback seed if every live source fails and no odds.json exists yet.
# (2026 Open Championship, via CBS Sports/FanDuel, as of Jul 14 2026 — will go stale fast.)
SEED_ODDS = {
    "Scottie Scheffler": "+700",
    "Rory McIlroy": "+850",
    "Tommy Fleetwood": "+1500",
    "Matt Fitzpatrick": "+1500",
    "Jon Rahm": "+2000",
    "Xander Schauffele": "+2700",
    "Collin Morikawa": "+3000",
    "Viktor Hovland": "+3000",
    "Robert MacIntyre": "+3000",
    "Wyndham Clark": "+3300",
    "Ludvig Åberg": "+3300",
    "Justin Rose": "+3300",
}


def normalize_name(name):
    name = name.strip()
    return NAME_MAP.get(name, name)


def fmt_odds(price):
    """Convert integer to American odds string."""
    try:
        n = int(price)
        return f"+{n}" if n >= 0 else str(n)
    except Exception:
        return None


def load_existing():
    """Load existing odds.json as a base."""
    try:
        with open(OUTPUT_FILE) as f:
            data = json.load(f)
        return data.get("odds", {})
    except Exception:
        return {}


def save_odds(odds_dict, source):
    data = {
        "odds": odds_dict,
        "exportedAt": datetime.datetime.utcnow().isoformat() + "Z",
        "source": source,
        "note": "Generated by fetch_odds.py — push to GitHub root.",
    }
    with open(OUTPUT_FILE, "w") as f:
        json.dump(data, f, indent=2)
    print(f"✓ Saved {len(odds_dict)} players to {OUTPUT_FILE}")
    print(f"  Source: {source}")


# ── Text parser ───────────────────────────────────────────────────────────────
def parse_odds_from_text(text):
    """
    Parse player odds from free-text pages.
    Handles patterns like:
      "Scottie Scheffler +700"
      "Rory McIlroy +850"
      "Scottie Scheffler     +700"
    """
    odds = {}
    # Each name word: leading capital, then letters/periods/apostrophes/hyphens —
    # this allows Mc/Mac names (McIlroy, MacIntyre), initials (J.T., J.J.), and
    # accented characters (Åberg, Højgaard, Välimäki), not just all-lowercase tails.
    pattern = re.compile(
        r'([A-Z\u00C0-\u024F][A-Za-z\u00C0-\u024F\'.-]*'
        r'(?:[ \t]+[A-Z\u00C0-\u024F][A-Za-z\u00C0-\u024F\'.-]*){1,3})'
        r'[ \t]{0,10}([+-]\d{3,6})\b'
    )
    for match in pattern.finditer(text):
        name = normalize_name(match.group(1).strip())
        price_str = match.group(2)
        if len(name) < 8:
            continue
        try:
            val = int(price_str)
            if abs(val) < 100:
                continue  # odds are always >=100, this filters out golf scores like -8/+3
        except Exception:
            continue
        formatted = fmt_odds(val)
        if formatted:
            if name not in odds or abs(val) < abs(int(odds[name])):
                odds[name] = formatted
    return odds


def scrape_url(url, min_players=10):
    r = requests.get(url, headers=HEADERS, timeout=15)
    if r.status_code != 200:
        print(f"    HTTP {r.status_code}")
        return None
    soup = BeautifulSoup(r.text, "html.parser")
    text = soup.get_text(" ", strip=True)
    odds = parse_odds_from_text(text)
    if len(odds) >= min_players:
        return odds
    print(f"    Only parsed {len(odds)} players, need >= {min_players} — skipping")
    return None


# ── Source 1: CBS Sports (primary article) ────────────────────────────────────
def try_cbssports_primary():
    print("  Trying CBS Sports (primary odds article)...")
    url = "https://www.cbssports.com/golf/news/2026-open-championship-picks-predictions-odds-field-course-favorites-contenders/"
    try:
        odds = scrape_url(url)
        if odds:
            print(f"  ✓ Got {len(odds)} players from CBS Sports (primary)")
            return odds, "CBS Sports (primary)"
    except Exception as e:
        print(f"  CBS Sports (primary) failed: {e}")
    return None


# ── Source 2: CBS Sports (secondary/backup article) ───────────────────────────
def try_cbssports_secondary():
    print("  Trying CBS Sports (secondary odds article)...")
    url = "https://www.cbssports.com/golf/news/2026-british-open-betting-odds-rory-mcilroy-scottie-scheffler/"
    try:
        odds = scrape_url(url)
        if odds:
            print(f"  ✓ Got {len(odds)} players from CBS Sports (secondary)")
            return odds, "CBS Sports (secondary)"
    except Exception as e:
        print(f"  CBS Sports (secondary) failed: {e}")
    return None


# ── Source 3: Bleacher Report ─────────────────────────────────────────────────
def try_bleacherreport():
    print("  Trying Bleacher Report...")
    url = "https://bleacherreport.com/articles/25454211-british-open-2026-field-odds-favorites-and-tournament-preview"
    try:
        odds = scrape_url(url)
        if odds:
            print(f"  ✓ Got {len(odds)} players from Bleacher Report")
            return odds, "Bleacher Report"
    except Exception as e:
        print(f"  Bleacher Report failed: {e}")
    return None


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print("=" * 50)
    print("2026 Open Championship Odds Fetcher")
    print("=" * 50)

    existing = load_existing()
    print(f"Existing odds.json: {len(existing)} players\n")

    result = None
    for source_fn in [try_cbssports_primary, try_cbssports_secondary, try_bleacherreport]:
        result = source_fn()
        if result:
            break
        print()

    if result:
        new_odds, source_name = result
        # Merge: new data wins, keep existing for any players not found
        merged = {**existing, **new_odds}
        save_odds(merged, source_name)
        print("\nTop 10 odds:")
        sorted_odds = sorted(merged.items(), key=lambda x: int(x[1].replace("+", "")))
        for name, odds in sorted_odds[:10]:
            print(f"  {name:<30} {odds}")
    else:
        print("\n⚠ All sources failed. Keeping existing odds.json unchanged.")
        print("  You can manually update odds.json with the current lines.")
        if not existing:
            print("  No existing odds found — creating with seed data.")
            save_odds(SEED_ODDS, "Manual seed")


if __name__ == "__main__":
    main()