name: Test Schedule

"on":
  schedule:
    - cron: '3 * * * *'
    - cron: '13 * * * *'
    - cron: '23 * * * *'
    - cron: '33 * * * *'
    - cron: '43 * * * *'
    - cron: '53 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print info
        run: |
          echo "Event: ${{ github.event_name }}"
          date -u